### ISSUE TITLE
ModuleNotFoundError: No module named 'mehr_plate'

### ISSUE THREAD

**Issue by Deltaplc** [ThoreMehr/Mehr_BoxMaker#2]
I cannot use this extension ..... This error always occurs. Can you help me?

Traceback (most recent call last):
  File "mehrbox.py", line 24, in <module>
    import mehr_plate
ModuleNotFoundError: No module named 'mehr_plate'

**Comment by ThoreMehr** [comment]
There are two .PY files in the repository. One is the one you are missing.
You need both in the extension folder.

Deltaplc <notifications@github.com> schrieb am Mi., 3. Feb. 2021, 06:49:

**Comment by Deltaplc** [comment]
Hi
I checked in case I made a mistake copying the files .....
There are both .PY files but unfortunately the error persists !!

**Comment by robkern** [comment]
@Deltaplc After installing the Mehr BoxMaker extension in Inkscape V1.0.2 on Mac according to [this generic documentation](https://inkscape.org/gallery/=extension/) and starting the preview of the box maker I received a similar error
```
Traceback (most recent call last):
  File "mehr_box_maker.py", line 24, in <module>
    import fablabchemnitz_mehr_plate
ModuleNotFoundError: No module named 'fablabchemnitz_mehr_plate'
```

I was finally able to resolve the error by performing the following steps:
1. Copy file `https://gitea.fablabchemnitz.de/MarioVoigt/mightyscape-1.X/src/branch/master/extensions/fablabchemnitz/mehrbox/mehr_plate.py` into the inkscape extension folder.
2. Rename the file into `fablabchemnitz_mehr_plate.py`.
3. Restart inkscape.
